### ISSUE TITLE
[SE-1] Enhancement of the experience

### ISSUE THREAD

**Issue by iHRex** [iHRex/school-management#1]
Basic up-gradation of the interface of the sidebar appearance of the use-panel.

![Screenshot 2024-01-01 033551](https://github.com/iHRex/school-management/assets/14982304/fba2f43f-6606-479f-badb-717b32e4c5e6)

**Comment by Yatin12527** [comment]
if you can specify the upgradations im happy to work on it.

**Comment by shera-bhai** [comment]
I would love to take over this issue and make it more reasonable and interactive for the users!

Please let me know your thoughts on this proposal, and if you have any specific preferences or additional requirements. I am eager to contribute to the continuous improvement!

Thank you for considering this request. I look forward to your feedback.

Best regards,
Shera Bhai

**Comment by iHRex** [comment]
@shera-bhai  @Yatin12527 

Hello, 
Thank you for showing interest, the proposed changes(deemed) are as follows:-

- The arrangement of the box in a minimized way
- Changing the default structure to Class>> Attendance
                                                                  >> Marks etc..

**Comment by shera-bhai** [comment]
@iHRex 

Nice to hear from you,

It will be a piece for cake for these things to be implemented. Will make sure to help you out but rn I have been assigned an other project, so as u also know can't take up many at once. I'll approach you soon after completing it!

Best Regards,
Shera Bhai

**Comment by Yatin12527** [comment]
> @shera-bhai @Yatin12527
> 
> Hello, Thank you for showing interest, the proposed changes(deemed) are as follows:-
> 
> * The arrangement of the box in a minimized way
> * Changing the default structure to Class----->> Attendance
>   -------------------------------------------------->> Marks etc..
> * Using icons to enhance user experience
> * Using minimalist animation
> 
> PS: Do let me know if you have a better idea, welcome!

i apologize i've been assigned few other issues if i find the issue opened after fixing those i'd surely love to work on this.

**Comment by flux30** [comment]
I'm interested in contributing to the problem.

**Comment by iHRex** [comment]
@flux30 

Regards, you have been assigned the issue.

**Comment by kamalsritha** [comment]
can you please assign me this issue under SWOC.

**Comment by iHRex** [comment]
Hello @kamalsritha ,

Apology, the issue has been already assigned to @flux30.

Requesting you to please have a look at other issues.
__
**HARSH V**
Project Admin
School Management System EMS
