### ISSUE TITLE
codeql feature  add

### ISSUE THREAD

**Issue by pinak22dhir** [iHRex/school-management#12]
Describe the solution you'd like
I want to add the codeql workflow to automate security checks. CodeQL is the code analysis engine developed by GitHub to identify vulnerabilities in code. It will analyze your code and display the results as code scanning alerts. It will be enabled on every push, commit and pull request using GitHub actions.

**Comment by iHRex** [comment]
Assigned.
Please use the [Pull Request Template ](https://github.com/iHRex/school-management/blob/main/PR.md)

**Comment by iHRex** [comment]
Pull added, and closed
