### ISSUE TITLE
[BE-1] Unresopnsive and glitchy form

### ISSUE THREAD

**Issue by iHRex** [iHRex/school-management#2]
There are multiple issues in the form section of the add support staff segment

1. DOB select dialog box doesn't appear in mobile interface
2. The image upload option isn't visible

(can be assigned to multiple)

![image](https://github.com/iHRex/school-management/assets/14982304/775f85e9-2c11-4b9e-8e8a-55b71a4cb67d)

**Comment by sidharth2829** [comment]
I would like to work on this issue . Please assign me this under SWOC'24.

**Comment by vrun1208** [comment]
@iHRex , Hi!, i want to work on this issue

**Comment by shera-bhai** [comment]
Hey @iHRex 👋 

Sorry for coming up late, but as I can see Issue #1 has been assigned to someone else.

This is the only issue left, so if you could lemme work up on this issue.. it'll be grateful!

I look forward to your response! Thanks for Concerning..

Best Regards,
**Shera Bhai**

**Comment by shera-bhai** [comment]
Hey @iHRex 

Thnks for assigning the issue.

Do we dont have any other way to debug the code, as the WordPress asks to Upgrade to Creator Plan to Install Plugins!

**Comment by iHRex** [comment]
Hello @shera-bhai

You can use ***WordPress Playground for VSCode*** add-on, which is available for free on Visual Studio Marketplace.

Or use the link: https://marketplace.visualstudio.com/items?itemName=WordPressPlayground.wordpress-playground

**Comment by kamalsritha** [comment]
can you please assign me this issue under SWOC.

**Comment by shera-bhai** [comment]
@iHRex 

Thnks for the help, initiating a PR to this issue!
