### ISSUE TITLE
Missing CONTRIBUTING.md File in Repository

### ISSUE THREAD

**Issue by suhanipaliwal** [iHRex/school-management#39]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

**Comment by iHRex** [comment]
@suhanipaliwal 

Assigned

**Comment by suhanipaliwal** [comment]
Could you please add the label of appropriate level like level 1, 2 or 3 on this issue.

**Comment by iHRex** [comment]
@suhanipaliwal 

Usually this kind of issues aren't counted in point table, but assuming that you are new to open source, I am allocating level 1 to the issue.

Regards
