### ISSUE TITLE
[Documentation]-Needs Corrections and Modifications

### ISSUE THREAD

**Issue by AdityaP700** [iHRex/school-management#51]
# Title:  [Documentation]-Necessary Edits
## Description:
Documentation of a project plays a major role in showcasing your ideas to clients; therefore, it is important to have an extensive, crisp, and readable file.
## Describe the bug in detail, like a detective on the case!
-    During a review of the documented files—PR.md, README.md, and CONTRIBUTING.md— i pointed out several issues . 
- These issues include formatting typographical errors in the documents. Correcting these flaws is essential to ensuring the documentation is both extensive and error-free.
##  Can you replicate the bug? Show us the steps to reproduce it.
    Access_the_Repository:
        - Clone the repository from GitHub 
        - Open the Documentation Files
        -Navigate to the directory containing the documentation files (`PR.md`, `README.md`, and `CONTRIBUTING.md`). and  reviewing the Files for :

- Missing punctuation.
- Incorrect usage of markdown syntax.
- Typographical errors in the text.

 ## ✅ What were you expecting to happen?
- Consistency
- Clarity
- Professionalism
  - ❌ What actually happened instead? Let's see that glitch!
   ->![image](https://github.com/iHRex/school-management/assets/126982848/6b0c6ec2-9252-485b-9fb4-35fce533414f)
    One of the example where the header text have been modified so that it can be easy to read and visually appealing.
![image](https://github.com/iHRex/school-management/assets/126982848/e847743c-93f2-49cb-8342-b3110e09450a)
 These are some of the images ,i am working behind some of them but in my cloned personal repository . If  i have your permissions i can push it to the main branch..
   - Images are worth a thousand bug reports (if applicable).
   ->
   - Code snippets can help pinpoint the culprit (if applicable).
   ->

#### Version:

WordPress_version: 6.1.1
PHP_Version: 8.0.3
DB_Version_if_configured: MySQL 8.0.25

#### Labels:

   >Add relevant labels to help us categorize the bug (e.g., bug, high priority).

#### Tracker
> Kindly do not alter details below
- [x] Valid
- [x] Assigned
- [x] PR Generated
- [x] Verified and Merged
- [x] Dispose

#### Workflow
```mermaid
graph LR
Gen[Issue Generated] --> Check{Valid?} -- Yes --> Validate{Validate}
Check -- No --> Dispose((Dispose))
Validate -- Agssign --> PR[Pull Request] -- verified --> Merged
PR -- changes required --> Wait(Wait) -- Reassigned --> Validate
Wait -- no response --> Dispose
```

**Comment by AdityaP700** [comment]
Well i have expertise in formatting the Documentation files in some of the Projects i have worked on ,if you let me assign me this role i can assure you that i will provide you a formatted and edited documented file. Thanks

**Comment by iHRex** [comment]
@AdityaP700 

Assigned, go ahead.

**Comment by AdityaP700** [comment]
Alright Thanks @iHRex , i am working on it .
