### ISSUE TITLE
Mobile number error fixing

### ISSUE THREAD

**Issue by Sumitshvr** [iHRex/school-management#53]
The mobile number has a fatal error as it's not taking an input. With my experience in php as i have done two dbms projects in php assign me the issue.
![Screenshot 2024-05-18 110040](https://github.com/iHRex/school-management/assets/118909272/52b04a1c-5253-4c22-a2ea-1ef3dc0d8bb8)

**Comment by iHRex** [comment]
Hello @Sumitshvr 

Issue assigned, the level will be added after analysing the efforts required and severity by mentors.

Thank you!

**Comment by Sumitshvr** [comment]
assign the issue

**Comment by apekkshaa** [comment]
@Sumitshvr can you tell me if you have already identified the reason for issue, or if you have begun analysing it? so that I can proceed to decide which level is to be assigned

**Comment by iHRex** [comment]
There is some issues mapping the country code, using country.xml

**Comment by iHRex** [comment]
Hello @apekkshaa,

I'd request you to please go through the pr, in my analysis- the assignee has created another object of country and country code in the code itself. Whereas, this was needed to be fetched from a default entity [country.xml]

**Comment by Sumitshvr** [comment]
Hello @apekkshaa 
The main reason for the error +<!DOCTYPE html><html lang= in the mobile number input field was likely due to the smgt_get_countery_phonecode() function returning unexpected HTML content instead of just the country code and regarding the country.xml file its not working i tried with json file also still there is the same issue likewise for the xml file.

**Comment by Sumitshvr** [comment]
Hello @iHRex 
 With respect to my issue of mobile number input field i have solved that issue.  I hope you will look into it.
 Also if there is need to fix the file issue we can create a new issue and can work on it or object of country and country code in the code itself will be good

**Comment by iHRex** [comment]
Hello @Sumitshvr 

Reviewed and merged. Thank you!
