### ISSUE TITLE
[Feat]: Auto Commenting Feat for Issue Creation

### ISSUE THREAD

**Issue by Asymtode712** [iHRex/school-management#56]
# Title:  Auto Commenting Feat for Issue Creation

#### Description:

   - This feature aims to address the problem of delayed and inconsistent communication following the creation of issues. By automatically commenting on issues as soon as they are created, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.
   
# Screenshot

![issue creation](https://github.com/iHRex/school-management/assets/115717746/5dc24d69-493f-4ddc-b9de-965b1ec64a0c)

**Comment by Asymtode712** [comment]
@iHRex Why?? Don't you want to automate this repo for better communication?

**Comment by iHRex** [comment]
@Asymtode712 

I'd request you to take over Issue #59 https://github.com/iHRex/school-management/issues/59
