### ISSUE TITLE
Actions: Multiple automation

### ISSUE THREAD

**Issue by iHRex** [iHRex/school-management#59]
# Actions: Multiple automation

#### Job:
- [ ] Auto Commenting Feat for Issue Creation
- [ ] Auto Commenting feature for PR Merged
- [ ] Auto Commenting feature for PR Raised

#### Tracker
> Kindly do not alter details below
- [x] Valid
- [x] Assigned
- [ ] PR Generated
- [ ] Verified and Merged
- [ ] Dispose

**Comment by Asymtode712** [comment]
@iHRex please assign me this issue

**Comment by iHRex** [comment]
Hello @Asymtode712 

Issue assigned.

**Comment by Asymtode712** [comment]
@iHRex please add the relevant level label

**Comment by Asymtode712** [comment]
**Step 1: Create a Personal Access Token (PAT) with repo Permission**


**1. Navigate to Settings:**

 - Click on your profile picture in the upper-right corner of the page.
 - Select "Settings" from the dropdown menu.

**2. Go to Developer Settings:**

- In the left sidebar, scroll down and click on "Developer settings."

**3. Create a New Token:**

- Click on "Personal access tokens" in the left sidebar.
- Click on the "Generate new token" button.

**4. Configure the Token:**

- Token Description: Enter a descriptive name for the token (e.g., Repo Access Token).
- Expiration: Set no expiration.
- Select Scopes: Check the box next to repo to grant full control of private repositories.

**5. Generate Token:**

- Scroll down and click on the "Generate token" button.
- Important: Copy the token to a secure location. You will not be able to see it again once you navigate away from the page.
<br>

**Step 2: Assign the Token to GITHUB_TOKEN Environment Variable**

**1. Navigate to Your Repository:**

- Go to your repository on GitHub.
- Click on the "Settings" tab.

**2. Go to Secrets:**

- In the left sidebar, click on "Secrets and variables" and then "Actions".

**3. Create a New Secret:**

- Click on the "New repository secret" button.
- Name: Enter GITHUB_TOKEN.
- Value: Paste your generated token.
- Click on the "Add secret" button.
