### ISSUE TITLE
Update the Contributing steps with command palette 

### ISSUE THREAD

**Issue by Sibam-Paul** [iHRex/school-management#62]
# Title: To update the Contributing with more details and commands 

#### Description:

   - Describe the bug in detail, like a detective on the case!
   -> Not a detailed contributing steps mentioned for OS contribution 
   - Can you replicate the bug? Show us the steps to reproduce it.
   -> I can add details about contributing steps with commands as in the pic below
   - ✅ What were you expecting to happen?
![image](https://github.com/iHRex/school-management/assets/158052549/ef799e02-6bd8-484f-be2a-6de615787735)

   - ❌ What actually happened instead? Let's see that glitch!
![image](https://github.com/iHRex/school-management/assets/158052549/4227dccc-50f0-499c-b5ae-e64906abca92)

#### Labels:

   > Documentation, GSSOC'24, Level 1

_Please assign me this issue under GSSOC'24 as I want to work on this_

**Comment by apekkshaa** [comment]
@Sibam-Paul assigned

**Comment by Sibam-Paul** [comment]
ok

**Comment by Sibam-Paul** [comment]
@iHRex Can u please tell me how to run locally??

**Comment by iHRex** [comment]
@Sibam-Paul 

My email is already mentioned in the readme.md

**Comment by Sibam-Paul** [comment]
ok

**Comment by Sibam-Paul** [comment]
@iHRex Please review my pull request
