### ISSUE TITLE
New UI for School management login page

### ISSUE THREAD

**Issue by MitulSonagara** [iHRex/school-management#64]
# Title:  Concise yet informative description of the bug

#### Description:

   - Describe the bug in detail, like a detective on the case!
   -> School management login page ui is not so good.

   - Can you replicate the bug? Show us the steps to reproduce it.
   ->I will change that UI according to your website.

   - Images are worth a thousand bug reports (if applicable).
   ->
![image](https://github.com/iHRex/school-management/assets/95460188/fa137354-e384-42ed-a777-1cfec6b31bce)

#### Version:

- WordPress version: 
- PHP Version:
- DB Version(if configured): 

#### Labels:

   >Add relevant labels to help us categorize the bug (e.g., bug, high priority).

#### Tracker
> Kindly do not alter details below
- [ ] Valid
- [ ] Assigned
- [ ] PR Generated
- [ ] Verified and Merged
- [ ] Dispose

#### Workflow
```mermaid
graph LR
Gen[Issue Generated] --> Check{Valid?} -- Yes --> Validate{Validate}
Check -- No --> Dispose((Dispose))
Validate -- Agssign --> PR[Pull Request] -- verified --> Merged
PR -- changes required --> Wait(Wait) -- Reassigned --> Validate
Wait -- no response --> Dispose
```

**Comment by apekkshaa** [comment]
@MitulSonagara assigned

**Comment by MitulSonagara** [comment]
@apekkshaa sorry for inconvenience I am not able to do this. So i am unassigning this. You can assign this to anyone else.

**Comment by iHRex** [comment]
This isn't applicable.
