### ISSUE TITLE
Footer Links Not Redirecting to Respective Pages

### ISSUE THREAD

**Issue by aslams2020** [iHRex/school-management#67]
Hi @iHRex,
Here is the issue i encountered - 
**Title:** Footer Links Not Redirecting to Respective Pages

**Description:**

The links in the footer section for "Privacy Policy," and "Terms and Conditions" are currently non-functional. 
They do not redirect to the respective pages as expected. This issue needs to be addressed by creating the respective pages and linking them correctly.

**To Reproduce**
- Go to the website's homepage or any page with the footer.
- Scroll down to the footer section.
- Click on the "Privacy Policy," or "Terms and Conditions" links.
- Observe that nothing happens, and the user is not redirected to any respective page

**Expected behavior**
Clicking on the "Privacy," "Privacy Policy," or "Terms and Conditions" links in the footer should redirect the user to the respective pages containing the relevant information.

**Advantages of Resolving the Footer Links Issue**
1. Improved User Experience
2. Legal Compliance
3. Enhanced Navigation
4. Professionalism
5. User Trust and Credibility

i hope i was able to address the issue to you.
if so, Could you please assign this issue to me under GSSoC?

**Comment by Henin-6024** [comment]
I would like to contribute for this project. Please assign this task to me under GSSoC'24 with required labels.
@iHRex

**Comment by apekkshaa** [comment]
@aslams2020 assigned

**Comment by aslams2020** [comment]
hello @apekkshaa, For some reason, I am unable to proceed with this issue as I am having difficulties handling the PHP code. 
Please unassign this issue from me.

Thank you for understanding.
