### ISSUE TITLE
Plugin Installation Error 

### ISSUE THREAD

**Issue by Newbie4newthings** [iHRex/school-management#77]
# Title:  Concise yet informative description of the bug

#### Description:

   - Describe the bug in detail, like a detective on the case!
   -> When trying to upload the plugin into WordPress, i get an error, "The link you followed has expired."
   - Can you replicate the bug? Show us the steps to reproduce it.
   -> Yes, Just try uploading the plugin 
   - ✅ What were you expecting to happen?
   -> 
   - ❌ What actually happened instead? Let's see that glitch!
   ->
   - Images are worth a thousand bug reports (if applicable).
   -> 
![image](https://github.com/user-attachments/assets/4af1ce68-77a8-4370-9e9f-ee48468ef931)
![Screenshot 2024-10-14 065848](https://github.com/user-attachments/assets/aa38c2bc-c037-4b84-80b7-0f3037a544aa)

   - Code snippets can help pinpoint the culprit (if applicable).
   ->

#### Version:

- WordPress version: 6.6.2
- PHP Version:
- DB Version(if configured): 

#### Labels:

   >Add relevant labels to help us categorize the bug (e.g., bug, high priority).

#### Tracker
> Kindly do not alter details below
- [ ] Valid
- [ ] Assigned
- [ ] PR Generated
- [ ] Verified and Merged
- [ ] Dispose

#### Workflow
```mermaid
graph LR
Gen[Issue Generated] --> Check{Valid?} -- Yes --> Validate{Validate}
Check -- No --> Dispose((Dispose))
Validate -- Agssign --> PR[Pull Request] -- verified --> Merged
PR -- changes required --> Wait(Wait) -- Reassigned --> Validate
Wait -- no response --> Dispose
```

**Comment by iHRex** [comment]
Hi,

You are required to increase the upload limit.  This is a logical issue.

Thanks and regards!
HARSH V

**Comment by Newbie4newthings** [comment]
hey, 

Thank you, i guess that would sort it out, was trying to test the plugin with a free hosting service.
